### ISSUE TITLE
found unknown escape character while parsing a quoted scalar

### ISSUE THREAD

**Issue by pj42** [volanja/ansible_spec#119]
This ansible variable causes an error in version 0.2.25 of ansible_spec but was working ok in version 0.2.24 and below:

    value: '\.(?:gz)$'

Error trace:

    On host `localhost'
    Failure/Error: vars = AnsibleSpec.get_variables(host, group_idx)
    Psych::SyntaxError:
      (<unknown>): found unknown escape character while parsing a quoted scalar at line 7 column 14
    
    # /usr/local/rvm/gems/ruby-2.3.0/gems/ansible_spec-0.2.25/lib/ansible_spec/load_ansible.rb:486:in `resolve_variables'
    # /usr/local/rvm/gems/ruby-2.3.0/gems/ansible_spec-0.2.25/lib/ansible_spec/load_ansible.rb:551:in `get_variables'

**Comment by volanja** [comment]
This issue has been marked as stale because it has not had recent activity.
It will be closed if no further activity occurs.
Thank you for your contributions.
