### ISSUE TITLE
Inventory children of children not honoured - how to work around this ?

### ISSUE THREAD

**Issue by itsme-narahari** [volanja/ansible_spec#137]
Hello:

Thanks in advance for your time and attention.

The inventory looks like this
```
[A_DMGR_GROUP]
abc.cool.com  ansible_host=100.8.168.173

[A_NODES_SET1_GROUP]
abc.cool.com  ansible_host=100.8.168.173

[A_NODES_SET2_GROUP]
def.cool.com  ansible_host=100.8.168.183

[A_NODES_GROUP:children]
A_NODES_SET1_GROUP
A_NODES_SET2_GROUP

[A_SERVERS_GROUP:children]
A_DMGR_GROUP
A_NODES_GROUP
```

When I run `rake -T`

I see this error
```
(?-mix::children)
A_NODES_GROUP:children
A_NODES_SET1_GROUP
A_NODES_SET2_GROUP
(?-mix::children)
A_SERVERS_GROUP:children
A_DMGR_GROUP
{"name"=>"A_NODES_GROUP", "port"=>22, "connection"=>"ssh", "uri"=>"A_NODES_GROUP"}
rake aborted!
TypeError: no implicit conversion of nil into Array
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:115:in `+'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:115:in `block in get_parent'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:114:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:114:in `get_parent'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:86:in `block in load_targets'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:80:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:80:in `load_targets'
/usr/local/lib/ruby/gems/2.7.0/gems/ansible_spec-0.3.2/lib/ansible_spec/load_ansible.rb:428:in `get_properties'
/Users/nlakshmi/samples/server_spec/Rakefile:6:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

Please suggest how to get around.

**Comment by volanja** [comment]
`ansible_spec` is not support children of children.
The workaround is nothing.
