### ISSUE TITLE
if hosts not matched, puts fail message

### ISSUE THREAD

**Issue by volanja** [volanja/ansible_spec#36]
If `hosts` on playbook don't match group on inventoryfile, puts fail message.

```
fail "no hosts matched"
```

Now, puts `NoMethodError`

```
$ rake -T --trace
rake aborted!
NoMethodError: undefined method `each' for "xxx":String
/Users/Adr/Development/vagrant_list/ansible-Redmine/Rakefile:12:in `block (2 levels) in <top (required)>'
/Users/Adr/Development/vagrant_list/ansible-Redmine/Rakefile:11:in `each'
/Users/Adr/Development/vagrant_list/ansible-Redmine/Rakefile:11:in `block in <top (required)>'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/task_manager.rb:209:in `in_namespace'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/dsl_definition.rb:146:in `namespace'
/Users/Adr/Development/vagrant_list/ansible-Redmine/Rakefile:10:in `<top (required)>'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:687:in `raw_load_rakefile'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:93:in `load_rakefile'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:77:in `block in run'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/bin/rake:23:in `load'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/bin/rake:23:in `<main>'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/Adr/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by phiche** [comment]
This change breaks my use case with a dynamic inventory where it is not a failure condition for no hosts to be matched in a playbook. We do not expect every host to be present in a development environment on EC2. I have raised https://github.com/volanja/ansible_spec/issues/49 and submitted a pull request to correct this.
