### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass if inventory has "roles"=>[]

### ISSUE THREAD

**Issue by phiche** [volanja/ansible_spec#47]
If for some reason the roles list for a host is empty, ansible_spec dies with ```NoMethodError: undefined method `each' for nil:NilClass```

Here is an example that produces the error
{"name"=>"No-roles-playbook", "hosts"=>["127.0.0.1"], "roles"=>[], "sudo"=>true}

```
rake aborted!
NoMethodError: undefined method `each' for nil:NilClass
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/ansible_spec-0.2.2/lib/ansible_spec/load_ansible.rb:203:in `flatten_role'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/ansible_spec-0.2.2/lib/ansible_spec/load_ansible.rb:185:in `block in load_playbook'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/ansible_spec-0.2.2/lib/ansible_spec/load_ansible.rb:184:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/ansible_spec-0.2.2/lib/ansible_spec/load_ansible.rb:184:in `load_playbook'
/usr/local/rvm/gems/ruby-2.0.0-p643/gems/ansible_spec-0.2.2/lib/ansible_spec/load_ansible.rb:233:in `get_properties'
```

**Comment by volanja** [comment]
I released [v0.2.3](https://rubygems.org/gems/ansible_spec/versions/0.2.3)
Thank you :)
